[tasks.build]
command = "cargo"
args = ["build", "--release"]


[tasks.run]
command = "cargo"
args = ["run", "--release"]

[tasks.book-storage-deploy]
command = "sh"
args = ["-c", "ENV_FILE=\"../../../powerwand/.env\"; touch \"$ENV_FILE\"; chmod +w \"$ENV_FILE\"; cp ~/dev/keypairs-test/book_storage-keypair.json ~/dev/the-archive/hogwarts-lib-rs/target/deploy; anchor deploy --program-name book-storage --program-keypair ~/dev/keypairs-test/book_storage-keypair.json --provider.wallet ~/.solana-keypair/account0/keypair 2>&1 | tee /tmp/anchor_output.log; sleep 2; PROGRAM_ID=$(grep -o 'Program Id: [A-Za-z0-9]*' /tmp/anchor_output.log | awk '{print $3}'); echo \"Extracted Program ID: $PROGRAM_ID\"; if [ -n \"$PROGRAM_ID\" ]; then sed -i 's/^BOOK_STORAGE_PROGRAM_ID=.*/BOOK_STORAGE_PROGRAM_ID='\"$PROGRAM_ID\"'/' \"$ENV_FILE\"; sync; else echo \"❌ Failed to extract Program ID\" >&2; exit 1; fi"]
cwd = "../hogwarts-lib-rs/programs/book-storage"

[tasks.book-cover-deploy]
command = "sh"
args = ["-c", "ENV_FILE=\"../../../powerwand/.env\"; touch \"$ENV_FILE\"; chmod +w \"$ENV_FILE\"; cp ~/dev/keypairs-test/book_storage-keypair.json ~/dev/the-archive/hogwarts-lib-rs/target/deploy; anchor deploy --program-name book-cover --program-keypair ~/dev/keypairs-test/book_cover-keypair.json --provider.wallet ~/.solana-keypair/account0/keypair 2>&1 | tee /tmp/anchor_output.log; sleep 2; PROGRAM_ID=$(grep -o 'Program Id: [A-Za-z0-9]*' /tmp/anchor_output.log | awk '{print $3}'); echo \"Extracted Program ID: $PROGRAM_ID\"; if [ -n \"$PROGRAM_ID\" ]; then sed -i 's/^BOOK_COVER_PROGRAM_ID=.*/BOOK_COVER_PROGRAM_ID='\"$PROGRAM_ID\"'/' \"$ENV_FILE\"; sync; else echo \"❌ Failed to extract Program ID\" >&2; exit 1; fi"]
cwd = "../hogwarts-lib-rs/programs/book-cover"

[tasks.mpl-token-metadata-deploy]
command = "sh"
args = ["-c", "ENV_FILE=~/dev/the-archive/powerwand/.env; touch \"$ENV_FILE\"; chmod +w \"$ENV_FILE\"; echo \"🔄 Fetching mpl-token-metadata program from Mainnet...\"; solana program dump -u mainnet-beta metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s mpl_token_metadata.so; echo \"🚀 Deploying mpl-token-metadata to Localnet...\"; solana program deploy mpl_token_metadata.so --program-id ~/dev/keypairs-test/mpl-token-metadata-keypair.json 2>&1 | tee /tmp/mpl_metadata_output.log; sleep 2; MPL_TOKEN_METADATA_PROGRAM_ID=$(grep -o 'Program Id: [A-Za-z0-9]*' /tmp/mpl_metadata_output.log | awk '{print $3}'); echo \"Extracted Metaplex Program ID: $MPL_TOKEN_METADATA_PROGRAM_ID\"; if [ -n \"$MPL_TOKEN_METADATA_PROGRAM_ID\" ]; then sed -i 's/^MPL_TOKEN_METADATA_PROGRAM_ID=.*/MPL_TOKEN_METADATA_PROGRAM_ID='\"$MPL_TOKEN_METADATA_PROGRAM_ID\"'/' \"$ENV_FILE\"; sync; else echo \"❌ Failed to extract Metaplex Program ID\" >&2; exit 1; fi"]
cwd = "../hogwarts-lib-rs/target/deploy"
