[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
book-storage = "Fk3qBVpk9KCYunBMcdaCcUm3wA9zj7rgBtdu7mBU6CHc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.solana-keypair/account0/keypair"

[scripts]
# Deploy
book-storage-deploy = "anchor build --program-name book-storage && anchor deploy --program-name book-storage --provider.wallet ~/.solana-keypair/account0/keypair"
