[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
book-storage = "8Besjdk7LVmnJfuCKAaM2sfAubbggvhgT597XFH8AXbj"
book-cover = "CLcPEsey6Ej423NZWnX7WnxVvE6Adirry8psgET3tiiG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.solana-keypair/account0/keypair"

[scripts]
book-storage-deploy = "anchor build --program-name book-storage && anchor deploy --program-name book-storage --provider.wallet ~/.solana-keypair/account0/keypair"
